### ISSUE TITLE
make_error_code is undeclared?

### ISSUE THREAD

**Issue by shrinktofit** [boostorg/system#114]
My compiler(Visual Studio 2022) said the `make_error_code` is undeclared here:

https://github.com/boostorg/system/blob/b0ef682e3d94f98478c00513ea7819f384a36f83/include/boost/system/detail/error_code.hpp#L142-L151

I searched for this symbol, I saw it's defined in: `boost::system::errc` and `boost::system::windows_error` etc. It certainly cannot be found within `boost::system` namespace(L150).

**Comment by pdimov** [comment]
What program are you trying to compile?

**Comment by shrinktofit** [comment]
I'm writing a program involving boost.beast, which then is referring to boost.system via:

![image](https://github.com/boostorg/system/assets/28807867/5e135038-c95a-40b2-814a-b2bd747cc775)

and then the above error is given:

```
out\build\x64-debug\vcpkg_installed\x64-windows\include\boost\system\detail\error_code.hpp(150): error C3861: “make_error_code”: Could not find the identifier.
```

**Comment by pdimov** [comment]
The `make_error_code` overloads for `boost::asio::error` are here: https://github.com/boostorg/asio/blob/28ff1e7c2b44f141eb809abaf2d76c95f38350ca/include/boost/asio/error.hpp#L334-L356

`make_error_code(e)` should find them via argument-dependent lookup.

**Comment by shrinktofit** [comment]
Thank you @pdimov  . I must have encountered some language specific problem. Let me digit into it. :)
