### ISSUE TITLE
not building with cmake

### ISSUE THREAD

**Issue by Duron27** [boostorg/system#123]
not sure why but libboost_system.a never gets created using cmake with clang

**Comment by pdimov** [comment]
System is header-only. The b2 build only creates the library for backward compatibility, it doesn't do anything when linked.

**Comment by Duron27** [comment]
the program I'm building is older and requires it. is there a way I can create it or fake it?

**Comment by Duron27** [comment]
for searchability this seems to do the trick so far
llvm-ar rc libboost_system.a find / -name "error_code.o"
