### ISSUE TITLE
1.69.0: error_code: Warnings about non-virtual destructor

### ISSUE THREAD

**Issue by myrkr** [boostorg/system#35]
When I compile boost 1.69.0 with the -Wnon-virtual-dtor option enabled gcc 6.3.0 gives the following warning (or error if -Werror is active):

```
.../boost/_/include/boost/system/error_code.hpp:167:28: error: 'class boost::system::error_category' has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
 class BOOST_SYMBOL_VISIBLE error_category
                            ^~~~~~~~~~~~~~
.../boost/_/include/boost/system/error_code.hpp:275:28: error: base class 'class boost::system::error_category' has accessible non-virtual destructor [-Werror=non-virtual-dtor]
 class BOOST_SYMBOL_VISIBLE generic_error_category: public error_category
                            ^~~~~~~~~~~~~~~~~~~~~~
.../boost/_/include/boost/system/error_code.hpp:275:28: error: 'class boost::system::detail::generic_error_category' has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
.../boost/_/include/boost/system/error_code.hpp:295:28: error: base class 'class boost::system::error_category' has accessible non-virtual destructor [-Werror=non-virtual-dtor]
 class BOOST_SYMBOL_VISIBLE system_error_category: public error_category
                            ^~~~~~~~~~~~~~~~~~~~~
.../boost/_/include/boost/system/error_code.hpp:295:28: error: 'class boost::system::detail::system_error_category' has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
cc1plus: all warnings being treated as errors

```

I worked around the problem by adding the according pragmas disabling the diagnostic to the whole file.

I don't know if the combination of virtual methods (name in the case of error_category) with non-virtual destructor is problematic here. But if not, it would be nice of this kind of warnings could be disabled for the code as there are other reports out there, see https://github.com/facebook/folly/issues/990 for example.

**Comment by pdimov** [comment]
The destructor is only accessible under C++03: https://github.com/boostorg/system/blob/develop/include/boost/system/error_code.hpp#L191-L206

The default for gcc 6 is C++14. Under what conditions does this happen?

**Comment by myrkr** [comment]
The problem is reproducible with a file containing:

`#include <boost/system/error_code.hpp>`

and a compiler run `g++ -c -Wnon-virtual-dtor test.cp test.cpp`.

Maybe the compiler warns about that the (implicit) default constructor is subject to the same limitation?

I have added more information including the output of "-E -dD" in this location: [README describing this issue](https://raw.githubusercontent.com/myrkr/temp/master/README.boost-system-issue-35)

**Comment by pdimov** [comment]
`-Wnon-virtual-dtor` is not even in `-Wextra`, which is why I wasn't seeing it. I'll look into this.

**Comment by pdimov** [comment]
Should be fixed on master and develop, and in the upcoming 1.70.

**Comment by vient** [comment]
I assume this is the same warning that happens now with gcc 13.2 and boost 1.83 https://godbolt.org/z/b668MbhEo

**Comment by pdimov** [comment]
Please see https://github.com/boostorg/system/issues/83.
