### ISSUE TITLE
error_code_test has a locale-dependent test

### ISSUE THREAD

**Issue by Kojoley** [boostorg/system#39]
https://github.com/boostorg/system/blob/0134441a6e628f407e77275b675e9a5757f65c0a/test/error_code_test.cpp#L200

It is an only failure I observe in the test file.

**Comment by pdimov** [comment]
There is a check for English here:

https://github.com/boostorg/system/blob/0134441a6e628f407e77275b675e9a5757f65c0a/test/system_error_test.cpp#L38-L46

but not there, I'm not sure why. I'll look into it.
