### ISSUE TITLE
VS 2019 Warning C26812

### ISSUE THREAD

**Issue by rchalamala** [boostorg/system#51]
The enum type 'boost::system::errc::errc_t' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).
Can the error code be converrted to enum class?

**Comment by ayush0x00** [comment]
You might be using enum EnumName {option1,option2}. With C++ 11, enum is being destined to be used as class for security reasons.
Try using enum class EnumName {option1,option2}

**Comment by pdimov** [comment]
Boost.System supports C++03, and `enum class` requires C++11.
