### ISSUE TITLE
use of "id" as variable name causes objective-c compiler problems

### ISSUE THREAD

**Issue by LostVector** [boostorg/system#52]
"id" is a reserved keyword in objective-c / c++.  It is used as a variable name in the following header/function:

https://github.com/boostorg/system/blob/develop/include/boost/system/error_code.hpp#L782-L807

It appears some objective-c compilers can deal with this, but also some clearly can not.

I ran across this issue because I was using boost asio, and at some point between 1.65 and 1.72 it included the aforementioned header, which caused compilation to break.

Patching the variable name to "cat_id" fixes the issue.

**Comment by pdimov** [comment]
What specific errors did you get?

**Comment by LostVector** [comment]
Expected unqualified-id before ‘=‘ at line 790 in error_code.hpp.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pdimov** [comment]
Should be fixed now. Thanks for the report.
