### ISSUE TITLE
windows_error.hpp deprecation warning

### ISSUE THREAD

**Issue by johnwason** [boostorg/system#57]
I saw the deprecation warning during a build when using `windows_error.hpp`. I am still using the Windows error codes for interacting with LibUSB and other low-level functions. I can work around it but it would be easier to not have this removed. I suspect a lot of other people are using it for some niche purposes.

**Comment by pdimov** [comment]
Thanks for the feedback! I will remove the deprecation notice from `windows_error.hpp`. Out of curiosity, is your code using it publicly available?

**Comment by johnwason** [comment]
No, I don't have anything open source using it right now.
