### ISSUE TITLE
linux_error.hpp deprecation

### ISSUE THREAD

**Issue by maximilianriemensberger** [boostorg/system#77]
When updating to boost 1.78 from an older version, inoticed that commit https://github.com/boostorg/system/commit/8f32183b63b478a1b3474f4c01e931d2821a5787 introduced deprecation warnings for the platform specific error code.  I'm using linux_error.hpp to detect non-fatal errors when accepting TCP sockets.  There are a few of those defined in linux_error.hpp

Is it be possible to un-deprecate the header (similarly to https://github.com/boostorg/system/issues/57)?

**Comment by pdimov** [comment]
Yes of course.
